# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlmofireObjectmapperDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  use_frameworks!

  # Pods for AlmofireObjectmapperDemo

  target 'AlmofireObjectmapperDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlmofireObjectmapperDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
